#include "B_TREE.h"

int main()
{
	Tree T;
	//m = 3
	T.insertTree(3, 30);
	T.show();
	cout << endl;
	T.insertTree(3, 20);
	T.show();
	cout << endl;
	T.insertTree(3, 62);
	T.show();
	cout << endl;
	T.insertTree(3, 110);
	T.show();
	cout << endl;
	T.insertTree(3, 140);
	T.show();
	cout << endl;
	T.insertTree(3, 15);
	T.show();
	cout << endl;
	T.insertTree(3, 65);
	T.show();
	cout << endl;
	T.insertTree(3, 136);
	T.show();
	cout << endl;
	T.insertTree(3, 150);
	T.show();
	cout << endl;
	T.insertTree(3, 120);
	T.show();
	cout << endl;
	T.insertTree(3, 40);
	T.show();
	cout << endl;
	T.insertTree(3, 132);
	T.show();
	cout << endl;
	T.insertTree(3, 19);
	T.show();
	cout << endl;
	T.insertTree(3, 128);
	T.show();
	cout << endl;
	T.insertTree(3, 138);
	T.show();
	cout << endl;
	T.insertTree(3, 100);
	T.show();
	cout << endl;
	T.insertTree(3, 16);
	T.show();
	cout << endl;
	T.insertTree(3, 145);
	T.show();
	cout << endl;
	T.insertTree(3, 70);
	T.show();
	cout << endl;
	T.insertTree(3, 42);
	T.show();
	cout << endl;

	T.insertTree(3, 69);
	T.show();
	cout << endl;
	T.insertTree(3, 43);
	T.show();
	cout << endl;
	T.insertTree(3, 26);
	T.show();
	cout << endl;
	T.insertTree(3, 60);
	T.show();
	cout << endl;
	T.insertTree(3, 130);
	T.show();
	cout << endl;
	T.insertTree(3, 50);
	T.show();
	cout << endl;
	T.insertTree(3, 18);
	T.show();
	cout << endl;
	T.insertTree(3, 7);
	T.show();
	cout << endl;
	T.insertTree(3, 36);
	T.show();
	cout << endl;
	T.insertTree(3, 58);
	T.show();
	cout << endl;

	T.insertTree(3, 22);
	T.show();
	cout << endl;
	T.insertTree(3, 41);
	T.show();
	cout << endl;
	T.insertTree(3, 59);
	T.show();
	cout << endl;
	T.insertTree(3, 57);
	T.show();
	cout << endl;
	T.insertTree(3, 54);
	T.show();
	cout << endl;
	T.insertTree(3, 33);
	T.show();
	cout << endl;
	T.insertTree(3, 75);
	T.show();
	cout << endl;
	T.insertTree(3, 124);
	T.show();
	cout << endl;
	T.insertTree(3, 122);
	T.show();
	cout << endl;
	T.insertTree(3, 123);
	T.show();
	cout << endl;

	//삭제
	T.deleteTree(3, 40);
	T.show();
	cout << endl;
	T.deleteTree(3, 132);
	T.show();
	cout << endl;
	T.deleteTree(3, 19);
	T.show();
	cout << endl;
	T.deleteTree(3, 128);
	T.show();
	cout << endl;
	T.deleteTree(3, 138);
	T.show();
	cout << endl;
	T.deleteTree(3, 100);
	T.show();
	cout << endl;
	T.deleteTree(3, 16);
	T.show();
	cout << endl;
	T.deleteTree(3, 145);
	T.show();
	cout << endl;
	T.deleteTree(3, 70);
	T.show();
	cout << endl;
	T.deleteTree(3, 42);
	T.show();
	cout << endl;
	T.deleteTree(3, 22);
	T.show();
	cout << endl;
	T.deleteTree(3, 41);
	T.show();
	cout << endl;
	T.deleteTree(3, 62);
	T.show();
	cout << endl;
	T.deleteTree(3, 110);
	T.show();
	cout << endl;
	T.deleteTree(3, 140);
	T.show();
	cout << endl;
	T.deleteTree(3, 15);
	T.show();
	cout << endl;
	T.deleteTree(3, 65);
	T.show();
	cout << endl;
	T.deleteTree(3, 124);
	T.show();
	cout << endl;
	T.deleteTree(3, 122);
	T.show();
	cout << endl;
	T.deleteTree(3, 123);
	T.show();
	cout << endl;
	T.deleteTree(3, 30);
	T.show();
	cout << endl;
	T.deleteTree(3, 20);
	T.show();
	cout << endl;
	T.deleteTree(3, 59);
	T.show();
	cout << endl;
	T.deleteTree(3, 57);
	T.show();
	cout << endl;
	T.deleteTree(3, 54);
	T.show();
	cout << endl;
	T.deleteTree(3, 33);
	T.show();
	cout << endl;
	T.deleteTree(3, 75);
	T.show();
	cout << endl;
	T.deleteTree(3, 136);
	T.show();
	cout << endl;
	T.deleteTree(3, 150);
	T.show();
	cout << endl;
	T.deleteTree(3, 120);
	T.show();
	cout << endl;
	T.deleteTree(3, 69);//
	T.show();
	cout << endl;
	T.deleteTree(3, 43);
	T.show();
	cout << endl;
	T.deleteTree(3, 26);
	T.show();
	cout << endl;
	T.deleteTree(3, 60);
	T.show();
	cout << endl;
	T.deleteTree(3, 130);
	T.show();
	cout << endl;
	T.deleteTree(3, 50);
	T.show();
	cout << endl;
	T.deleteTree(3, 18);
	T.show();
	cout << endl;
	T.deleteTree(3, 7);
	T.show();
	cout << endl;
	T.deleteTree(3, 36);
	T.show();
	cout << endl;
	T.deleteTree(3, 58);
	T.show();
	cout << endl;

	Tree f;
	//m = 4
	f.insertTree(4, 30);
	f.show();
	cout << endl;
	f.insertTree(4, 20);
	f.show();
	cout << endl;
	f.insertTree(4, 62);
	f.show();
	cout << endl;
	f.insertTree(4, 110);
	f.show();
	cout << endl;
	f.insertTree(4, 140);
	f.show();
	cout << endl;
	f.insertTree(4, 15);
	f.show();
	cout << endl;
	f.insertTree(4, 65);
	f.show();
	cout << endl;
	f.insertTree(4, 136);
	f.show();
	cout << endl;
	f.insertTree(4, 150);
	f.show();
	cout << endl;
	f.insertTree(4, 120);
	f.show();
	cout << endl;
	f.insertTree(4, 40);
	f.show();
	cout << endl;
	f.insertTree(4, 132);
	f.show();
	cout << endl;
	f.insertTree(4, 19);
	f.show();
	cout << endl;
	f.insertTree(4, 128);
	f.show();
	cout << endl;
	f.insertTree(4, 138);
	f.show();
	cout << endl;
	f.insertTree(4, 100);
	f.show();
	cout << endl;
	f.insertTree(4, 16);
	f.show();
	cout << endl;
	f.insertTree(4, 145);
	f.show();
	cout << endl;
	f.insertTree(4, 70);
	f.show();
	cout << endl;
	f.insertTree(4, 42);
	f.show();
	cout << endl;

	f.insertTree(4, 69);
	f.show();
	cout << endl;
	f.insertTree(4, 43);
	f.show();
	cout << endl;
	f.insertTree(4, 26);
	f.show();
	cout << endl;
	f.insertTree(4, 60);
	f.show();
	cout << endl;
	f.insertTree(4, 130);
	f.show();
	cout << endl;
	f.insertTree(4, 50);
	f.show();
	cout << endl;
	f.insertTree(4, 18);
	f.show();
	cout << endl;
	f.insertTree(4, 7);
	f.show();
	cout << endl;
	f.insertTree(4, 36);
	f.show();
	cout << endl;
	f.insertTree(4, 58);
	f.show();
	cout << endl;

	f.insertTree(4, 22);
	f.show();
	cout << endl;
	f.insertTree(4, 41);
	f.show();
	cout << endl;
	f.insertTree(4, 59);
	f.show();
	cout << endl;
	f.insertTree(4, 57);
	f.show();
	cout << endl;
	f.insertTree(4, 54);
	f.show();
	cout << endl;
	f.insertTree(4, 33);
	f.show();
	cout << endl;
	f.insertTree(4, 75);
	f.show();
	cout << endl;
	f.insertTree(4, 124);
	f.show();
	cout << endl;
	f.insertTree(4, 122);
	f.show();
	cout << endl;
	f.insertTree(4, 123);
	f.show();
	cout << endl;

	//삭제
	f.deleteTree(3, 40);
	f.show();
	cout << endl;
	f.deleteTree(3, 132);
	f.show();
	cout << endl;
	f.deleteTree(3, 19);
	f.show();
	cout << endl;
	f.deleteTree(3, 128);
	f.show();
	cout << endl;
	f.deleteTree(3, 138);
	f.show();
	cout << endl;
	f.deleteTree(3, 100);
	f.show();
	cout << endl;
	f.deleteTree(3, 16);
	f.show();
	cout << endl;
	f.deleteTree(3, 145);
	f.show();
	cout << endl;
	f.deleteTree(3, 70);
	f.show();
	cout << endl;
	f.deleteTree(3, 42);
	f.show();
	cout << endl;
	f.deleteTree(3, 22);
	f.show();
	cout << endl;
	f.deleteTree(3, 41);
	f.show();
	cout << endl;
	f.deleteTree(3, 62);
	f.show();
	cout << endl;
	f.deleteTree(3, 110);
	f.show();
	cout << endl;
	f.deleteTree(3, 140);
	f.show();
	cout << endl;
	f.deleteTree(3, 15);//1번 b = a -> b = a - 1
	f.show();
	cout << endl;
	f.deleteTree(3, 65);
	f.show();
	cout << endl;
	f.deleteTree(3, 124);
	f.show();
	cout << endl;
	f.deleteTree(3, 122);
	f.show();
	cout << endl;
	f.deleteTree(3, 123);
	f.show();
	cout << endl;
	f.deleteTree(3, 30);
	f.show();
	cout << endl;
	f.deleteTree(3, 20);
	f.show();
	cout << endl;
	f.deleteTree(3, 59);
	f.show();
	cout << endl;
	f.deleteTree(3, 57);
	f.show();
	cout << endl;
	f.deleteTree(3, 54);
	f.show();
	cout << endl;
	f.deleteTree(3, 33);
	f.show();
	cout << endl;
	f.deleteTree(3, 75);
	f.show();
	cout << endl;
	f.deleteTree(3, 136);
	f.show();
	cout << endl;
	f.deleteTree(3, 150);
	f.show();
	cout << endl;
	f.deleteTree(3, 120);
	f.show();
	cout << endl;
	f.deleteTree(3, 69);//
	f.show();
	cout << endl;
	f.deleteTree(3, 43);
	f.show();
	cout << endl;
	f.deleteTree(3, 26);
	f.show();
	cout << endl;
	f.deleteTree(3, 60);
	f.show();
	cout << endl;
	f.deleteTree(3, 130);
	f.show();
	cout << endl;
	f.deleteTree(3, 50);
	f.show();
	cout << endl;
	f.deleteTree(3, 18);
	f.show();
	cout << endl;
	f.deleteTree(3, 7);
	f.show();
	cout << endl;
	f.deleteTree(3, 36);
	f.show();
	cout << endl;
	f.deleteTree(3, 58);
	f.show();
	cout << endl;
	return 0;
}